In [11]:
from rl import run_inference, ThorNavEnv, CLIPCuriosity, ExtrinsicReward
from models import ActorCritic
from cons import DEVICE
import torch
import prior
from ai2thor.controller import Controller

dataset = prior.load_dataset("procthor-10k")
train_scenes = dataset["train"]

NUM_UPDATES = 100

idx = torch.randint(0, len(train_scenes), (1,)).item()
idx = 3
house = train_scenes[idx]

controller = Controller(
    scene=house,
    snapToGrid=False,
    rotateStepDegrees=30,
    renderDepthImage=True,
)



Fetching reference HEAD


[AI2-THOR WARNING] There has been an update to ProcTHOR-10K that must be used with AI2-THOR version 5.0+. To use the new version of ProcTHOR-10K, please update AI2-THOR to version 5.0+ by running:
    pip install --upgrade ai2thor
Alternatively, to downgrade to the old version of ProcTHOR-10K, run:
   prior.load_dataset("procthor-10k", revision="ab3cacd0fc17754d4c080a3fd50b18395fae8647")


Loading test: 100%|██████████| 1000/1000 [00:00<00:00, 22452.25it/s]


In [12]:

# Load trained model
actor_critic = ActorCritic().to(DEVICE)
actor_critic.load_state_dict(torch.load("data/ac_update_40.pt", map_location="cpu"))

clip_curiosity = CLIPCuriosity()
# Disable curiosity during inference
env = ThorNavEnv(controller, clip_curiosity=clip_curiosity, extrinsic_reward=ExtrinsicReward())

# Run inference
traj, total = run_inference(actor_critic, env, max_steps=256, deterministic=False)

print("Episode return:", total)

Episode return: 40.78855993751427


In [13]:
for i in traj:
    print(i["logits"].softmax(dim=1))

tensor([[0.5622, 0.2703, 0.1675]])
tensor([[0.6532, 0.2385, 0.1083]])
tensor([[0.6936, 0.2222, 0.0842]])
tensor([[0.7065, 0.2187, 0.0748]])
tensor([[0.7301, 0.2074, 0.0625]])
tensor([[0.7419, 0.2018, 0.0563]])
tensor([[0.7595, 0.1922, 0.0483]])
tensor([[0.7621, 0.1921, 0.0458]])
tensor([[0.7693, 0.1887, 0.0421]])
tensor([[0.7764, 0.1850, 0.0385]])
tensor([[0.7830, 0.1816, 0.0354]])
tensor([[0.7888, 0.1786, 0.0327]])
tensor([[0.7938, 0.1759, 0.0303]])
tensor([[0.7981, 0.1736, 0.0283]])
tensor([[0.8018, 0.1716, 0.0266]])
tensor([[0.8050, 0.1699, 0.0251]])
tensor([[0.8077, 0.1685, 0.0238]])
tensor([[0.8100, 0.1673, 0.0227]])
tensor([[0.8120, 0.1664, 0.0217]])
tensor([[0.8137, 0.1655, 0.0208]])
tensor([[0.8151, 0.1648, 0.0200]])
tensor([[0.8164, 0.1643, 0.0193]])
tensor([[0.8175, 0.1638, 0.0187]])
tensor([[0.8184, 0.1635, 0.0182]])
tensor([[0.8192, 0.1632, 0.0176]])
tensor([[0.8199, 0.1629, 0.0172]])
tensor([[0.8204, 0.1628, 0.0168]])
tensor([[0.8209, 0.1627, 0.0164]])
tensor([[0.8193, 0.1

In [1]:
controller.stop()

NameError: name 'controller' is not defined

In [22]:
a = torch.tensor([[0.33, 0.58, 0.11], [0.1, 0.9, 0]])

dist = torch.distributions.Categorical(probs=a)
dist.entropy(), torch.sum(-a * torch.log(a + 1e-8), dim=1)

(tensor([0.9263, 0.3251]), tensor([0.9246, 0.3251]))