In [1]:
from rl import run_inference, ThorNavEnv, CLIPCuriosity, ExtrinsicReward
from models import ActorCritic
from cons import DEVICE
import torch
import prior
from ai2thor.controller import Controller

dataset = prior.load_dataset("procthor-10k")
train_scenes = dataset["train"]

NUM_UPDATES = 100

idx = torch.randint(0, len(train_scenes), (1,)).item()
idx = 3
house = train_scenes[idx]

controller = Controller(
    scene=house,
    snapToGrid=False,
    rotateStepDegrees=30,
    renderDepthImage=True,
)



/Users/viriyadhika/Documents/5.UofT/Courses/CSC2503H-ComputerVision/Project/NavAssistant/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Fetching reference HEAD


[AI2-THOR WARNING] There has been an update to ProcTHOR-10K that must be used with AI2-THOR version 5.0+. To use the new version of ProcTHOR-10K, please update AI2-THOR to version 5.0+ by running:
    pip install --upgrade ai2thor
Alternatively, to downgrade to the old version of ProcTHOR-10K, run:
   prior.load_dataset("procthor-10k", revision="ab3cacd0fc17754d4c080a3fd50b18395fae8647")


Loading test: 100%|██████████| 1000/1000 [00:00<00:00, 23623.36it/s]


In [3]:

# Load trained model
actor_critic = ActorCritic().to(DEVICE)
actor_critic.load_state_dict(torch.load("data/ac_update_80.pt", map_location="cpu"))

clip_curiosity = CLIPCuriosity()
# Disable curiosity during inference
env = ThorNavEnv(controller, clip_curiosity=clip_curiosity, extrinsic_reward=ExtrinsicReward())

# Run inference
traj, total = run_inference(actor_critic, env, max_steps=256, deterministic=False)

print("Episode return:", total)

Episode return: 17.51381563950971


In [20]:
for i in traj:
    print(i["logits"].softmax(dim=1))

tensor([[0.3799, 0.3111, 0.3090]])
tensor([[0.4277, 0.2956, 0.2767]])
tensor([[0.4626, 0.2828, 0.2546]])
tensor([[0.4918, 0.2726, 0.2356]])
tensor([[0.5124, 0.2641, 0.2235]])
tensor([[0.5281, 0.2569, 0.2150]])
tensor([[0.5411, 0.2518, 0.2071]])
tensor([[0.5511, 0.2471, 0.2018]])
tensor([[0.5589, 0.2436, 0.1975]])
tensor([[0.5724, 0.2378, 0.1898]])
tensor([[0.5839, 0.2326, 0.1835]])
tensor([[0.5933, 0.2283, 0.1784]])
tensor([[0.6010, 0.2248, 0.1742]])
tensor([[0.6072, 0.2219, 0.1708]])
tensor([[0.6054, 0.2226, 0.1720]])
tensor([[0.6033, 0.2236, 0.1731]])
tensor([[0.6019, 0.2249, 0.1732]])
tensor([[0.6006, 0.2251, 0.1743]])
tensor([[0.5998, 0.2259, 0.1743]])
tensor([[0.5994, 0.2262, 0.1744]])
tensor([[0.6025, 0.2242, 0.1733]])
tensor([[0.6059, 0.2227, 0.1714]])
tensor([[0.6140, 0.2191, 0.1670]])
tensor([[0.6167, 0.2175, 0.1658]])
tensor([[0.6197, 0.2156, 0.1647]])
tensor([[0.6200, 0.2155, 0.1645]])
tensor([[0.6203, 0.2156, 0.1641]])
tensor([[0.6200, 0.2159, 0.1641]])
tensor([[0.6224, 0.2

In [1]:
controller.stop()

NameError: name 'controller' is not defined

In [22]:
a = torch.tensor([[0.33, 0.58, 0.11], [0.1, 0.9, 0]])

dist = torch.distributions.Categorical(probs=a)
dist.entropy(), torch.sum(-a * torch.log(a + 1e-8), dim=1)

(tensor([0.9263, 0.3251]), tensor([0.9246, 0.3251]))