In [1]:
from rl import run_inference, ThorNavEnv, CLIPCuriosity, ExtrinsicReward
from models import ActorCritic, SlidingWindowTransformerActorCritic
from cons import DEVICE, FEAT_DIM, NUM_ACTIONS
import torch
import prior
from ai2thor.controller import Controller

dataset = prior.load_dataset("procthor-10k")
train_scenes = dataset["train"]

NUM_UPDATES = 100

idx = torch.randint(0, len(train_scenes), (1,)).item()
idx = 3
house = train_scenes[idx]

controller = Controller(
    scene=house,
    snapToGrid=False,
    rotateStepDegrees=30,
    renderDepthImage=True,
)



/Users/viriyadhika/Documents/5.UofT/Courses/CSC2503H-ComputerVision/Project/NavAssistant/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Fetching reference HEAD


[AI2-THOR WARNING] There has been an update to ProcTHOR-10K that must be used with AI2-THOR version 5.0+. To use the new version of ProcTHOR-10K, please update AI2-THOR to version 5.0+ by running:
    pip install --upgrade ai2thor
Alternatively, to downgrade to the old version of ProcTHOR-10K, run:
   prior.load_dataset("procthor-10k", revision="ab3cacd0fc17754d4c080a3fd50b18395fae8647")


Loading test: 100%|██████████| 1000/1000 [00:00<00:00, 24630.50it/s]


In [2]:

# Load trained model
actor_critic = ac = SlidingWindowTransformerActorCritic(feat_dim=FEAT_DIM, num_actions=NUM_ACTIONS, device=DEVICE)
actor_critic.load_state_dict(torch.load("data/ac_update_30.pt", map_location="cpu"))

clip_curiosity = CLIPCuriosity()
# Disable curiosity during inference
env = ThorNavEnv(controller, clip_curiosity=clip_curiosity, extrinsic_reward=ExtrinsicReward())

# Run inference
traj, total = run_inference(actor_critic, env, max_steps=256, deterministic=False)

print("Episode return:", total)

Episode return: -2.0182384592494116


In [3]:
for i in traj:
    print(i["logits"].softmax(dim=1))

tensor([[0.6446, 0.2549, 0.1005]])
tensor([[0.6447, 0.2548, 0.1005]])
tensor([[0.6447, 0.2548, 0.1005]])
tensor([[0.6447, 0.2549, 0.1005]])
tensor([[0.6447, 0.2548, 0.1005]])
tensor([[0.6447, 0.2549, 0.1005]])
tensor([[0.6447, 0.2549, 0.1005]])
tensor([[0.6447, 0.2549, 0.1005]])
tensor([[0.6447, 0.2549, 0.1005]])
tensor([[0.6447, 0.2549, 0.1005]])
tensor([[0.6446, 0.2549, 0.1005]])
tensor([[0.6445, 0.2550, 0.1005]])
tensor([[0.6446, 0.2550, 0.1005]])
tensor([[0.6446, 0.2550, 0.1005]])
tensor([[0.6446, 0.2550, 0.1005]])
tensor([[0.6444, 0.2551, 0.1005]])
tensor([[0.6444, 0.2551, 0.1005]])
tensor([[0.6444, 0.2551, 0.1005]])
tensor([[0.6441, 0.2555, 0.1005]])
tensor([[0.6444, 0.2551, 0.1005]])
tensor([[0.6444, 0.2551, 0.1005]])
tensor([[0.6442, 0.2553, 0.1005]])
tensor([[0.6447, 0.2549, 0.1005]])
tensor([[0.6446, 0.2549, 0.1005]])
tensor([[0.6446, 0.2549, 0.1005]])
tensor([[0.6447, 0.2549, 0.1005]])
tensor([[0.6447, 0.2549, 0.1005]])
tensor([[0.6442, 0.2553, 0.1005]])
tensor([[0.6445, 0.2

In [1]:
controller.stop()

NameError: name 'controller' is not defined

In [22]:
a = torch.tensor([[0.33, 0.58, 0.11], [0.1, 0.9, 0]])

dist = torch.distributions.Categorical(probs=a)
dist.entropy(), torch.sum(-a * torch.log(a + 1e-8), dim=1)

(tensor([0.9263, 0.3251]), tensor([0.9246, 0.3251]))