In [4]:
from rl import run_inference, ThorNavEnv, CLIPCuriosity, ExtrinsicReward
from models import ActorCritic
from cons import DEVICE
import torch
import prior
from ai2thor.controller import Controller

dataset = prior.load_dataset("procthor-10k")
train_scenes = dataset["train"]

NUM_UPDATES = 100

idx = torch.randint(0, len(train_scenes), (1,)).item()
# idx = 3
house = train_scenes[idx]

controller = Controller(
    scene=house,
    snapToGrid=False,
    rotateStepDegrees=30,
    renderDepthImage=True,
)



Fetching reference HEAD


[AI2-THOR WARNING] There has been an update to ProcTHOR-10K that must be used with AI2-THOR version 5.0+. To use the new version of ProcTHOR-10K, please update AI2-THOR to version 5.0+ by running:
    pip install --upgrade ai2thor
Alternatively, to downgrade to the old version of ProcTHOR-10K, run:
   prior.load_dataset("procthor-10k", revision="ab3cacd0fc17754d4c080a3fd50b18395fae8647")


Loading test: 100%|██████████| 1000/1000 [00:00<00:00, 23279.70it/s]


In [7]:

# Load trained model
actor_critic = ActorCritic().to(DEVICE)
actor_critic.load_state_dict(torch.load("data/ac_update_10.pt", map_location="cpu"))

clip_curiosity = CLIPCuriosity()
# Disable curiosity during inference
env = ThorNavEnv(controller, clip_curiosity=clip_curiosity, extrinsic_reward=ExtrinsicReward())

# Run inference
traj, total = run_inference(actor_critic, env, max_steps=128, deterministic=False)

print("Episode return:", total)

Episode return: 92.53447768781912


In [8]:
for i in traj:
    print(i["logits"].softmax(dim=1))

tensor([[0.3553, 0.3373, 0.3074]])
tensor([[0.3996, 0.3240, 0.2764]])
tensor([[0.4596, 0.2986, 0.2418]])
tensor([[0.5414, 0.2601, 0.1984]])
tensor([[0.6183, 0.2218, 0.1599]])
tensor([[0.6687, 0.1974, 0.1340]])
tensor([[0.6890, 0.1887, 0.1223]])
tensor([[0.6938, 0.1875, 0.1187]])
tensor([[0.6946, 0.1877, 0.1177]])
tensor([[0.6943, 0.1878, 0.1179]])
tensor([[0.6942, 0.1878, 0.1180]])
tensor([[0.6939, 0.1880, 0.1181]])
tensor([[0.6937, 0.1881, 0.1182]])
tensor([[0.6936, 0.1881, 0.1182]])
tensor([[0.6933, 0.1880, 0.1187]])
tensor([[0.6932, 0.1880, 0.1188]])
tensor([[0.6933, 0.1877, 0.1190]])
tensor([[0.6933, 0.1876, 0.1191]])
tensor([[0.6934, 0.1876, 0.1191]])
tensor([[0.6933, 0.1877, 0.1190]])
tensor([[0.6932, 0.1878, 0.1189]])
tensor([[0.6933, 0.1877, 0.1190]])
tensor([[0.6933, 0.1876, 0.1190]])
tensor([[0.6933, 0.1878, 0.1189]])
tensor([[0.6933, 0.1879, 0.1189]])
tensor([[0.6933, 0.1879, 0.1189]])
tensor([[0.6936, 0.1880, 0.1184]])
tensor([[0.6933, 0.1880, 0.1187]])
tensor([[0.6934, 0.1

In [1]:
controller.stop()

NameError: name 'controller' is not defined

In [22]:
a = torch.tensor([[0.33, 0.58, 0.11], [0.1, 0.9, 0]])

dist = torch.distributions.Categorical(probs=a)
dist.entropy(), torch.sum(-a * torch.log(a + 1e-8), dim=1)

(tensor([0.9263, 0.3251]), tensor([0.9246, 0.3251]))